### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by isbincApps** [moritztng/prism#1]
first of all congratulate you for this incredible job.
second I want to know what images you use in https://prism.art/ as style

**Comment by moritztng** [comment]
Thank you! 🤗 

These are the images:

![pastell](https://user-images.githubusercontent.com/19519902/118543082-1b6a0180-b754-11eb-9c6f-d8bbda1a0074.jpg)
![structure](https://user-images.githubusercontent.com/19519902/118543424-8b788780-b754-11eb-86c9-aa669c83769e.jpg)
![cubism](https://user-images.githubusercontent.com/19519902/118543468-93382c00-b754-11eb-8ae7-0a0a9b46eeab.jpg)
