### ISSUE TITLE
when i try use python object "from style_transfer.learn import StyleTransfer"

### ISSUE THREAD

**Issue by will0331** [moritztng/prism#3]
Hi moritztng

I couldnt really do from style_transfer.learn import StyleTransfer
it shows 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-69-8f98f0da9fa3> in <module>()
----> 1 from style_transfer.learn import StyleTransfer

ModuleNotFoundError: No module named 'style_transfer'.

What shall I do ?

Cheers 
Will

**Comment by moritztng** [comment]
Hey will0331, 

did you install the package with `pip install git+https://github.com/moritztng/prism.git`?
Everything looks fine and I can't reproduce the error. Could you provide more information?

Best 
Moritz

**Comment by will0331** [comment]
Hi Moritz

Instead of pip install git+https://github.com/moritztng/prism.git
I download it and use  !pip install -e /content/gdrive/MyDrive/T/prism-master/. 
Lol , cause sometimes i can mess around when i use different laptop and while i dont have internet connection. 
I will try  pip install git+https://github.com/moritztng/prism.git again latter and see if it pops up the same error. 
By the way , great work. Your network work very well. In my opinion your network even better than those one need to top up credict like nightcafe and neuralstyle.art .  

Best 
Will

**Comment by moritztng** [comment]
Hey Will,

thank you. I'm glad you like my network. Unfortunately, I don't know why the error occurs and how to fix it.
Please tell me when you have solved the issue. 

Best
Moritz
